/*
 * Copyright (c) 2017 Qunar.com. All Rights Reserved.
 */
package org.qunar.plugin.mybatis.generator;

import com.intellij.openapi.project.Project;
import com.intellij.psi.PsiElement;
import com.intellij.sql.psi.SqlFile;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.qunar.plugin.bean.ModuleSetting;
import org.qunar.plugin.util.Modules;

/**
 * mybatis mapper generator
 *
 * Author: jianyu.lin
 * Date: 2016/12/22 Time: 下午2:58
 */
public abstract class AbstractGenerator {

    @NotNull
    protected final Project project;
    @NotNull
    protected final SqlFile sqlFile;
    protected final ModuleSetting moduleSetting;

    public AbstractGenerator(@NotNull Project project, @NotNull SqlFile sqlFile) {
        this.project = project;
        this.sqlFile = sqlFile;
        moduleSetting = Modules.getModuleSettingByElement(sqlFile);
    }

    /**
     * generate psi element
     * @return psi element generated by this plugin
     */
    @Nullable
    public abstract PsiElement generate();
}
